name: Build .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      name: checkout

    - name: setup .net
      uses: actions/setup-dotnet@v3

    - run: dotnet restore
      name: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore
      
    - name: dotnet test
      run: dotnet test --no-restore --verbosity normal
